import { DatabaseSync } from 'node:sqlite';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { config } from './config.mjs';
if (config.database !== ':memory:') mkdirSync(dirname(config.database), { recursive: true });
export const db = new DatabaseSync(config.database);
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL, company TEXT DEFAULT '', address TEXT DEFAULT '', created_at TEXT NOT NULL, trial_end TEXT NOT NULL, stripe_customer TEXT UNIQUE, subscription_id TEXT, plan TEXT DEFAULT 'trial', paid_until TEXT, ever_paid INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS identities (provider TEXT, subject TEXT, user_id TEXT REFERENCES users(id), PRIMARY KEY(provider,subject));
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), csrf TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS oauth_states (id TEXT PRIMARY KEY, browser_hash TEXT NOT NULL, provider TEXT NOT NULL, purpose TEXT NOT NULL, user_id TEXT, verifier TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mailboxes (user_id TEXT PRIMARY KEY REFERENCES users(id), provider TEXT NOT NULL, email TEXT NOT NULL, encrypted TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS domains (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), name TEXT NOT NULL, price INTEGER NOT NULL CHECK(price>0), currency TEXT DEFAULT 'USD', keywords TEXT DEFAULT '', created_at TEXT NOT NULL, UNIQUE(user_id,name));
CREATE TABLE IF NOT EXISTS prospects (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), domain_id TEXT REFERENCES domains(id) ON DELETE CASCADE, company TEXT NOT NULL, website TEXT NOT NULL, email TEXT DEFAULT '', source TEXT NOT NULL, source_url TEXT DEFAULT '', reason TEXT DEFAULT '', reviewed INTEGER DEFAULT 0, created_at TEXT NOT NULL, UNIQUE(user_id,domain_id,website));
CREATE TABLE IF NOT EXISTS drafts (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), domain_id TEXT REFERENCES domains(id), prospect_id TEXT REFERENCES prospects(id), subject TEXT NOT NULL, body TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(user_id,prospect_id));
CREATE TABLE IF NOT EXISTS sends (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), domain_id TEXT REFERENCES domains(id), prospect_id TEXT REFERENCES prospects(id), recipient TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL, reserved_at TEXT NOT NULL, sent_at TEXT, provider_id TEXT, error TEXT, campaign_key TEXT NOT NULL, sender_name TEXT NOT NULL, sender_company TEXT NOT NULL, sender_address TEXT NOT NULL, mailbox_email TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS checkout_sessions (user_id TEXT PRIMARY KEY REFERENCES users(id), session_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS suppressions (user_id TEXT REFERENCES users(id), email TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(user_id,email));
CREATE TABLE IF NOT EXISTS webhook_events (id TEXT PRIMARY KEY, received_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_domains_user ON domains(user_id);
CREATE INDEX IF NOT EXISTS idx_prospects_user ON prospects(user_id,domain_id);
CREATE INDEX IF NOT EXISTS idx_drafts_user ON drafts(user_id);
CREATE INDEX IF NOT EXISTS idx_sends_user_status ON sends(user_id,status);
CREATE INDEX IF NOT EXISTS idx_sends_status_reserved ON sends(status,reserved_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sends_active_recipient ON sends(user_id,domain_id,recipient) WHERE status IN ('queued','sending','sent','unknown');
PRAGMA optimize;`);
export const get = (sql, ...params) => db.prepare(sql).get(...params);
export const all = (sql, ...params) => db.prepare(sql).all(...params);
export const run = (sql, ...params) => db.prepare(sql).run(...params);
export function transaction(fn) { db.exec('BEGIN IMMEDIATE'); try { const value = fn(); db.exec('COMMIT'); return value; } catch (e) { db.exec('ROLLBACK'); throw e; } }
